### PR TITLE
Upgrade minimum APM version to 1.12.0

### PR DESCRIPTION
**Pull request by vhatsura**
Addresses #14

@glucaci, what is the flow to update the library version to HC 11?

### CODE REVIEW

**Comment by glucaci** [comment]
Thanks for fixing it.

HC11 is no the main branch and HC12 on version-2 branch

**Comment by glucaci** [comment]
hc/2.0.0-preview.2 is building

**Comment by vhatsura** [comment]
> HC11 is no the main branch and HC12 on version-2 branch

yeap, I spotted it, but the instrumentation for HC11 is also broken, and the question was whether it's needed to fix it or not?

**Comment by vhatsura** [comment]
and one more question, do you have any plan to release stable version?

**Comment by glucaci** [comment]
Hi @vhatsura, sorry for late answer, it will come this month, at least for hc-version-2 / HC > 12.x.x

**Pull request merged**
